# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS/Desktop/CS223_Project/CS223_project/CS223_project.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS/Desktop/CS223_Project/CS223_project/CS223_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP.PCLABS/Desktop/CS223_Project/Beti_Modules/RGB_display_8X8/display_8X8.sv
  D:/Users/TEMP.PCLABS/Desktop/CS223_Project/Beti_Modules/stepmotor_7seg/stepmotor.sv
  D:/Users/TEMP.PCLABS/Desktop/CS223_Project/Beti_Modules/stepmotor_7seg/SevSeg_4digit.sv
  D:/Users/TEMP.PCLABS/Desktop/CS223_Project/Beti_Modules/stepmotor_7seg/top.sv
}
read_xdc D:/Users/TEMP.PCLABS/Desktop/CS223_Project/Beti_Modules/RGB_display_8X8/top.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS/Desktop/CS223_Project/Beti_Modules/RGB_display_8X8/top.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
